---
# vars file for roles/mysql-exporter
mysqld_exporter_version: "0.14.0"
mysqld_exporter_bin: /usr/local/bin/mysqld_exporter
mysqld_exporter_user: mysqlexporter
mysqld_exporter_group: "{{ mysqld_exporter_user }}"
mysqld_exporter_dir_conf: /etc/mysqld_exporter

ssl_cert_dir: /etc/ssl/certs
mysqld_exporter_ssl_key: "{{ssl_cert_dir}}/tecnalis_mysql_exporter.key"
mysqld_exporter_ssl_cert: "{{ssl_cert_dir}}/tecnalis_mysql_exporter.crt"
mysqld_exporter_ssl_csr: "{{ssl_cert_dir}}/tecnalis_mysql_exporter.csr"

mysqld_exporter_web_yml_conf: "{{mysqld_exporter_dir_conf}}/web.yml"
mysqld_exporter_env_conf: "{{mysqld_exporter_dir_conf}}/db.env"
mysqld_exporter_args: "--web.config.file={{mysqld_exporter_web_yml_conf}} --collect.info_schema.processlist --collect.info_schema.innodb_metrics --collect.auto_increment.columns --collect.engine_innodb_status --collect.global_status --collect.global_variables --collect.info_schema.clientstats --collect.info_schema.tables --collect.info_schema.tables.databases=\"*\" --collect.info_schema.tablestats --collect.info_schema.userstats --collect.perf_schema.eventsstatements --collect.perf_schema.eventswaits --collect.perf_schema.file_events --collect.perf_schema.file_instances --collect.perf_schema.indexiowaits --collect.perf_schema.tableiowaits --collect.perf_schema.tablelocks --collect.slave_status"