### Explicación playbook: Este playbook se ha creado para la creacón de  'N' usuarios definidos en el fichero /etc/ansible/recursos/variables/vars2.yml que contendrá
### tantas entradas como usuarios se deseen crear. las variables declaradas contendrán lo siguiente:
### usuario: 'nombre_usuario' clave: 'valor clave pública usuario' También se define por defecto la creación del home y del fichero que alojará la clave pública.
### Se pueden definir tantas variables como se deseen y reutilizar este playbook para futuras configuraciones.
---
 - name: Playbook_chpass_root
   hosts: all
   remote_user: ansible
   become: true

   tasks:
     - name: Access secret from vault
       set_fact:
         ROOT_PASSWORD: "{{ lookup('password', 'secret_value') }}"   

     - name: Cambiar password de root
       ansible.builtin.user:
         name: root
         state: present
         password: "{{ ROOT_PASSWORD  | password_hash('sha512') }}"

