---
 - name: Modify session-timeout de los tomcats a 30 segundos
   hosts: all
   remote_user: ansible
   become: true
   tasks:
    - name: Sacamos el home de cada tomcat que se esta ejecutando en la maquina y los guardamos en la variable homes
      shell: ps -fe | grep tomcat | grep -v alira | grep java | grep -v grep | awk -F ' ' '{print $9}' | awk -F'=' '{print $2}' | cut -d '/' -f 1,2,3,4
      register: rutas

    - name: Modify timeout
      ansible.builtin.debug: 
        msg: Modificamos el valor del timeout de {{ item }}/web.xml le fijamos a 30
      loop: "{{ rutas.stdout_lines }}"
