---
 - name: Playbook_remove_sudoers_policy
   hosts: all
   remote_user: ansible
   become: true
   tasks:
     - name: Delete sudo policy
       community.general.sudoers:
         name: servicios-sudo
         state: absent
